### ISSUE TITLE
Subscriber: Support string for datasetId

### ISSUE THREAD

**Issue by jarped** [kartverket/geosynkronisering#101]

**Comment by kvold** [comment]
See also issue #92 
We do sync the same dataset to multiple databases through different deegree-servers using the same subscriber. So we will f.ex. have several instances of vann_norge in one geosyncDB.sqlite. This probably complicates matters.
This wasn't a problem with the coresubscriber which used xml-files since we could define the xml-file when adding a dataset.

**Comment by jarped** [comment]
We could possibly use the Name field for this. Allowing setting this when adding a dataset and starting jobs based on name.

**Comment by jarped** [comment]
We need syncing and deleting using name
