### ISSUE TITLE
Deegree: Test that it works for 1.2.3

### ISSUE THREAD

**Issue by jarped** [kartverket/geosynkronisering#128]
https://github.com/kartverket/geosynkronisering/releases/download/untagged-41d6ec2bf15be549328c/deegree-webservices-3.4.13_releasecantidate.war

**Comment by jarped** [comment]
Check version of Java/Tomcat

**Comment by kvold** [comment]
Done some further testing:
-deegree cant access the database from the server, but I can access the database via psql while on the server
-It uses tomcat 7.0 and openjdk 1.8.0, on Centos 7.
-I tried with the standard deegree on the same server and had the same problem
-So I tried to use this deegree version on two other servers, it worked. Though I couldn't test it thoroughly since those weren't test-servers.

So it seems to be a server problem, not a problem with this branch of deegree.

I've received a proper test server now, so I'll set it up and test deegree from that.
